### ISSUE TITLE
could  you provide the dataset train.h5?

### ISSUE THREAD

**Issue by lihao0374** [yucicheung/AdaptiveReconNet#1]

**Comment by yucicheung** [comment]
Sorry I'm not able to offer a handy dataset right now.

However, the dataset *train.h5* can be generated by running [generate_train.m](https://github.com/KuldeepKulkarni/ReconNet/blob/master/train/generate_train.m).

**Comment by yucicheung** [comment]
The `train.h5` file is too large to be uploaded, so instead I offered the code to generate `train.h5` and `test.h5` under folder **generate_h5**.
